name: Auto Build Image CI

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
      - release-*

permissions: write-all

jobs:
  call-workflow:
    uses: ./.github/workflows/call-release-image.yaml
    with:
      ref: ${{ github.event.inputs.ref }}
      suffix: 'ci'
      push: "false"
